from os import environ
from dotenv import load_dotenv

load_dotenv()
CSRF_ENABLED = True
SECRET_KEY = environ['SECRET_KEY']
ERROR_MESSAGE = 'error: {}'
GROUP_ID = environ['GROUP_ID']
VERIFICATION_RESPONSE = environ['VERIFICATION_RESPONSE']
ACCESS_TOKEN = environ['ACCESS_TOKEN']
API_VERSION = environ['API_VERSION']
SQLALCHEMY_DATABASE_URI = environ['SQLALCHEMY_DATABASE_URI']
PASSWORD_SALT = environ['PASSWORD_SALT']
SQLALCHEMY_TRACK_MODIFICATIONS = False
